name: khutaa
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state

  provider:
  shared_preferences:
  get_it:
  google_fonts:
  pedometer:
  flutter_speed_dial:
  font_awesome_flutter:
  sizer:
  permission_handler:
  firebase_auth:
  cloud_firestore:
  sentry_flutter: ^6.0.1 
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/app/
    - assets/art/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
